name = "free-the-web-apps"
main = ".output/server/index.mjs"
compatibility_date = "2024-10-08"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".output/public/"
binding = "ASSETS"

[[kv_namespaces]]
binding = "KV"
id = "9c6e1b4847c64fad99bfb808acfae039"

[observability]
enabled = true
