import userChromeCss from "./files/userChrome.css";
import userJs from "./files/user.js.txt";
import type { TargetInfos, WebsiteType } from "~~/types";

function psQuote(s: string): string {
  return s.replace(/'/g, "''");
}

function firefoxSetup(target: TargetInfos): string {
  if (target.bw !== "firefox") return "# Firefox setup skipped";

  return `Write-Host "\nSetting up Firefox..."
Start-Process -FilePath '${psQuote(target.path)}' -ArgumentList '-CreateProfile','FTWA' -Wait -NoNewWindow

$ProfileBase = Join-Path $env:APPDATA 'Mozilla\\Firefox\\Profiles'
$ProfileFolder = Get-ChildItem -Path $ProfileBase -Directory -Filter '*.FTWA' | Select-Object -First 1 -ExpandProperty FullName
if (-not $ProfileFolder) { throw 'FTWA Firefox profile not found.' }

$ChromeDir = Join-Path $ProfileFolder 'chrome'
New-Item -ItemType Directory -Force -Path $ChromeDir | Out-Null

@'
${userChromeCss}
'@ | Set-Content -Path (Join-Path $ChromeDir 'userChrome.css') -Encoding UTF8

@'
${userJs}
'@ | Set-Content -Path (Join-Path $ProfileFolder 'user.js') -Encoding UTF8

Write-Host "Firefox setup done."`;
}

export function windows({
  website,
  target,
}: {
  website: WebsiteType;
  target: TargetInfos;
}) {
  const safeName = website.name.replace(/[\\/:*?"<>|]/g, "");
  const fname = "ftwa-" + website.name.toLowerCase().replace(/[^a-z0-9]+/g, "-");

  let commandArgs = "";
  if (target.bw === "firefox") {
    commandArgs = `--no-remote -P "FTWA" "${website.url}"`;
  } else if (["chrome", "opera", "brave", "edge"].includes(target.bw)) {
    commandArgs = `--app=${website.url}`;
  }

  return `# Generated by FTWA (https://ftwa.mathix.dev)
# /u/ links are only available for 24h
# Check the app store for more apps: https://ftwa.mathix.dev/store

$ErrorActionPreference = 'Stop'

${firefoxSetup(target)}

Write-Host "\nCreating shortcut..."

$IconDir = Join-Path $env:LOCALAPPDATA 'FTWA\\icons'
New-Item -ItemType Directory -Force -Path $IconDir | Out-Null

$PngPath = Join-Path $IconDir '${fname}.png'
$IcoPath = Join-Path $IconDir '${fname}.ico'

Invoke-WebRequest -Uri '${website.logo}' -OutFile $PngPath -UseBasicParsing

# Wrap the PNG as a single-image ICO so Windows can use any size (incl. 256+)
Add-Type -AssemblyName System.Drawing
$Bmp = [System.Drawing.Bitmap]::FromFile($PngPath)
$IcoW = if ($Bmp.Width -ge 256) { [byte]0 } else { [byte]$Bmp.Width }
$IcoH = if ($Bmp.Height -ge 256) { [byte]0 } else { [byte]$Bmp.Height }
$Bmp.Dispose()

$PngBytes = [System.IO.File]::ReadAllBytes($PngPath)
$Ms = New-Object System.IO.MemoryStream
$Bw = New-Object System.IO.BinaryWriter($Ms)
$Bw.Write([uint16]0); $Bw.Write([uint16]1); $Bw.Write([uint16]1)
$Bw.Write($IcoW); $Bw.Write($IcoH); $Bw.Write([byte]0); $Bw.Write([byte]0)
$Bw.Write([uint16]1); $Bw.Write([uint16]32)
$Bw.Write([uint32]$PngBytes.Length); $Bw.Write([uint32]22)
$Bw.Write($PngBytes)
$Bw.Close()
[System.IO.File]::WriteAllBytes($IcoPath, $Ms.ToArray())
$Ms.Dispose()

$BrowserPath = '${psQuote(target.path)}'
if (-not (Test-Path $BrowserPath)) { throw "Browser not found: $BrowserPath" }

$ShortcutDir = [Environment]::GetFolderPath('Programs')
$ShortcutPath = Join-Path $ShortcutDir '${psQuote(safeName)}.lnk'

$WshShell = New-Object -ComObject WScript.Shell
$Shortcut = $WshShell.CreateShortcut($ShortcutPath)
$Shortcut.TargetPath = $BrowserPath
$Shortcut.Arguments = '${psQuote(commandArgs)}'
$Shortcut.IconLocation = $IcoPath
$Shortcut.Description = 'Generated by FTWA (https://ftwa.mathix.dev)'
$Shortcut.WorkingDirectory = (Split-Path $BrowserPath -Parent)
$Shortcut.Save()

Write-Host "Shortcut created: $ShortcutPath"
Write-Host "Search for '${psQuote(website.name)}' in the Start Menu."
`;
}
