import type { TargetInfos, WebsiteType } from "~~/types";

// Thanks to:
// https://apple.stackexchange.com/a/402653
// https://xuk.ai/blog/mac-apps-for-terminal.html

export function macos({
  website,
  target,
}: {
  website: WebsiteType;
  target: TargetInfos;
}) {
  const formattedName = website?.name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  const fname = "ftwa-" + formattedName;
  const safeLogo = website.logo.replace(/'/g, "%27");

  if (website?.logoSize < 1024) {
    return `echo 'This logo is too small for macOS. Please provide a 1024x1024px logo.';`;
  }

  return `#!/usr/bin/env bash
# This script is generated by FTWA
# /u/ links are only available for 24h
# Check the gallery to find more apps: https://ftwa.mathix.dev/#gallery

# Exit on error
set -e;

echo "\\nCreating desktop entry...";

# Creating a temporary directory
tmpdir="$(mktemp -d)";

# Downloading the icon
icon_path="$tmpdir/${fname}.png";
curl -fsSLo $icon_path '${safeLogo}';

# Creating the icon file
mkdir "$tmpdir/${fname}.iconset"
sips -z 16 16     $icon_path --out "$tmpdir/${fname}.iconset/icon_16x16.png";
sips -z 32 32     $icon_path --out "$tmpdir/${fname}.iconset/icon_16x16@2x.png";
sips -z 32 32     $icon_path --out "$tmpdir/${fname}.iconset/icon_32x32.png";
sips -z 64 64     $icon_path --out "$tmpdir/${fname}.iconset/icon_32x32@2x.png";
sips -z 128 128   $icon_path --out "$tmpdir/${fname}.iconset/icon_128x128.png";
sips -z 256 256   $icon_path --out "$tmpdir/${fname}.iconset/icon_128x128@2x.png";
sips -z 256 256   $icon_path --out "$tmpdir/${fname}.iconset/icon_256x256.png";
sips -z 512 512   $icon_path --out "$tmpdir/${fname}.iconset/icon_256x256@2x.png";
sips -z 512 512   $icon_path --out "$tmpdir/${fname}.iconset/icon_512x512.png";
cp $icon_path "$tmpdir/${fname}.iconset/icon_512x512@2x.png";
iconutil -c icns "$tmpdir/${fname}.iconset";

# Creating the .app folder
mkdir -p '/Applications/${fname}.app/Contents/MacOS' '/Applications/${fname}.app/Contents/Resources';

# Creating the Info.plist file
cat > '/Applications/${fname}.app/Contents/Info.plist' << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Created by FTWA (https://ftwa.mathix.dev) -->
<plist version="1.0">
  <dict>
      <key>CFBundleDisplayName</key>
      <string>${website.name}</string>
      <key>CFBundleExecutable</key>
      <string>${fname}.sh</string>
      <key>CFBundleIconFile</key>
      <string>${fname}</string>
      <key>CFBundleIdentifier</key>
      <string>dev.mathix.ftwa.${formattedName}</string>
  </dict>
</plist>
EOF

# Creating the executable file
cat > '/Applications/${fname}.app/Contents/MacOS/${fname}.sh' << EOF
#!/usr/bin/env bash
${target.path} --app='${website.url}'
EOF

# Making the file executable
chmod +x '/Applications/${fname}.app/Contents/MacOS/${fname}.sh';

# Moving the icon
mv "$tmpdir/${fname}.icns" '/Applications/${fname}.app/Contents/Resources/';

# Cleaning up
rm -r "$tmpdir";

echo 'Desktop entry created. Search for "${website.name}" in Spotlight.';`;
};
